apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
  - description: Some name
    name: person-name
    type: string
  steps:
  - args:
    - |-
      echo My name is $(inputs.params.person-name)
      echo ---------------------------------------
    command:
    - /bin/bash
    - -c
    image: quay.io/openshift/origin-cli:latest
    name: hello-world
  workspaces:
  - name: output