apiVersion: tekton.dev/v1beta1 
kind: TaskRun 
metadata:
  name: build-task-run 
spec: 
  serviceAccountName: pipeline
  taskRef: 
    kind: Task
    name: build
  workspaces: 
  - name: output
    persistentVolumeClaim:
      claimName: output-pvc