apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: person-name
    type: string
    default: John Doe
    description: Some name
  tasks:
  - name: build
    taskRef: 
      name: build-hello-world
    params:
    - name: person-name
      value: $(params.person-name)
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: deploy
    taskRef: 
      name: deploy-hello-world
    workspaces:
    - name: output
      workspace: shared-workspace
    runAfter:
    - build